### ISSUE TITLE
donor details

### ISSUE THREAD

**Issue by shangong** [TechLadies/reach-frontend#7]
Could you work on the donor details page?

**Comment by psjoshi20** [comment]
Hi shang, Is this above <Could you work on the donor details page? >
message meant   for me ?
I can start work on it. pls let me know.

**Comment by shangong** [comment]
To work on this, you'll need to do a request

POST /donors/details
Body
{
"donorIdNo": "[ic number]"
}

Response: donor's details and corresponding donations. With seeded data, use "S1234567A" as ic number and get https://github.com/TechLadies/reach-backend/issues/28.

**Comment by psjoshi20** [comment]
Does that mean I have to POST (http request) donor details  to  an API using react ?

**Comment by psjoshi20** [comment]
-ok. 
1)first step is to try POST API 
2)second step is to  fetch API POST /donors/details
3)third step is to  pass the donar details data
