### ISSUE TITLE
List of things to settle 

### ISSUE THREAD

**Issue by clukhei** [TechLadies/reach-frontend#8]
Write it down before I forget

Problems: certain fetch API on Master branch is not up to date with the latest API 

To do list:

1) Update Upload feature at frontend (after backend is fixed) 
2) Update the Dashboard API at frontend ( Ask Shang what startDate and endDate he uses, BUT I think the data is wiped out now , so wait for upload endpoint to be settled first)

**Comment by shangong** [comment]
/donation/dashboard request:
POST
Body
{
"startDate": "[YYYY-MM-DD]",
"endDate": "[YYYY-MM-DD format]"
}
